### ISSUE TITLE
Linking Entries to eachother

### ISSUE THREAD

**Issue by Lenitr** [aerni/statamic-factory#19]
Is it possible to populate a field containing entries of another collection?

I've already tried and tested this with Taxonomy terms, it works there whenever you use a set amount of slugs as possible options.
I tried doing the same thing with collections, but the connection there is invalid, it really needs the entry ID and doesn't support the slugs.

A lot of the collections I'm using have some sort of connection to at least 1 other one, so I'm really hoping i can generate the fake data for all those collections.

**Comment by aerni** [comment]
The only way to make this work is to pass IDs of existing entries. We could probably also introduce a method that gets all entries within the allowed collections of the entries fieldtype and randomly selects a defined amount of entries. Something like `factory: entries`. Feel free to create a PR for this.

**Comment by Lenitr** [comment]
Yeah, the existing entries was something I tried as a temporary thing, but it's not the most ideal solution.

I don't think I have time for it on very short-term, but I could have a look at it later (current Statamic project will be finished soon, next project I will have some time again). If you've reviewed/reworked the other pull request at that time, I can try to do it based on the way you've made those changes there 🙂

**Comment by aerni** [comment]
Linking other entries and terms will work with the next major release.
