### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by GuyVervillePerso** [aerni/statamic-factory#24]
Hi Aerni,

It seems impossible for now to install on a Statamic 5.

Problem 1
    - aerni/factory[dev-master, v1.5.0] require stillat/primitives ^1.4.1 -> satisfiable by stillat/primitives[v1.4.1].
    **- aerni/factory[dev-feature/refactor, v1.4.0] require statamic/cms ^4.0 -> found statamic/cms[v4.0.0-alpha.1, ..., 4.x-dev] but it conflicts with your root composer.json require (^5.0).**
    - aerni/factory[v1.0.0, ..., v1.1.0] require php ^7.4 -> **your php version (8.3.9) does not satisfy that requirement.**
    - aerni/factory v1.1.1 requires statamic/cms 3.0.* || 3.1.* -> found statamic/cms[v3.0.0-beta.1, ..., 3.1.x-dev] but it conflicts with **your root composer.json require (^5.0).**
    - aerni/factory[v1.2.0, ..., v1.3.0] require statamic/cms ^3.0 || ^3.1 || ^3.2 -> found statamic/cms[v3.0.0-beta.1, ..., 3.4.x-dev] but it conflicts with **your root composer.json require (^5.0).**
    - stillat/primitives[v1.3.0, ..., v1.4.1] require nikic/php-parser ^4.10.3 -> found nikic/php-parser[v4.10.3, ..., 4.x-dev] but the package is fixed to **v5.1.0 (lock file version)** by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires aerni/factory * -> satisfiable by aerni/factory[dev-feature/refactor, dev-master, v1.0.0, ..., v1.5.0, 9999999-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require aerni/factory:*" to figure out if any version is installable, or "composer require aerni/factory:^2.1" if you know which you need.

**Comment by aerni** [comment]
Just follow the instructions of that error and add `--with-all-dependencies`. So `composer require aerni/factory --with-all-dependencies` should do it.

**Comment by montemartin** [comment]
I'm having the same issue. `--with-add-dependencies` doesn't fix it because there is a conflict between package versions.

The issue is the `stillat/primitives` requires `"nikic/php-parser": "^4.10.3",` (i.e. it's locked to version 4 while multiple other packages in Statamic require ^5.0:
```
→composer depends nikic/php-parser
ajthinking/archetype      v2.0.0  requires nikic/php-parser (^5.0)
phpunit/php-code-coverage 11.0.5  requires nikic/php-parser (^5.0)
psy/psysh                 v0.12.4 requires nikic/php-parser (^5.0 || ^4.0)
sebastian/complexity      4.0.1   requires nikic/php-parser (^5.0)
sebastian/lines-of-code   3.0.1   requires nikic/php-parser (^5.0)
```
It seems this version won't work without `stillat/primitives` being updated.

**Comment by aerni** [comment]
Oh, you're right. I'm working on a refactor of this addon that likely won't be using `stillat/primitives` anymore. In meantime, I suggest you raise an issue here: https://github.com/Stillat/primitives/issues.

**Comment by montemartin** [comment]
FYI, John updated the dependencies in Primitives. https://github.com/Stillat/primitives/issues/9

Updating the required version to ^2.0 should fix the install issue.

**Comment by aerni** [comment]
Just released a fix. This should work now.
