### ISSUE TITLE
PHP version support

### ISSUE THREAD

**Issue by fbenas** [aerni/statamic-factory#5]
Hi,

Thanks for making and sharing this package, it looks super useful.

I was just looking at this and would like to use it in a project but currently it seems it only supports php versions ^7.4. Is this a hard requirement, based on specific use of php 7.4 only features? Is there any scope here to make changes so it supports php 7.3 as well?

On a related note, what are your thoughts on supporting php 8?

Thanks again!

**Comment by aerni** [comment]
Yes, PHP 7.4 is a hard requirement based on specific features.

Adding support for PHP 8 is probably fairly simple. I don't have time right now but will for sure add it in the future.
