### ISSUE TITLE
Add support for imported fieldsets

### ISSUE THREAD

**Issue by aerni** [aerni/statamic-factory#8]

**Comment by Lenitr** [comment]
I've been testing a bit with this addon in a new statamic project.

Right now it seems that whenever a fieldset is present in the blueprint (even when there's no factory settings for that fieldset), I get the error `Undefined array key "field"`.

The only solution so far seems to be to comment out any fieldsets from the blueprint when running the factory.

Do you think it could be an easy solution to simply ignore any fieldsets (I think they can be recognised by the `import` key) for now?

**Comment by Lenitr** [comment]
Allright, I'll try to do it (hopefully soon), I'll pass you a PR when it's done

**Comment by aerni** [comment]
Imported fieldsets will work with the next major release.
