### ISSUE TITLE
Faker formatter "randomElement" throwing exception

### ISSUE THREAD

**Issue by ddm-studio** [aerni/statamic-factory#9]
When I am using [randomElement ](https://fakerphp.github.io/formatters/numbers-and-strings/#randomelement) like below, the following exception is thrown: 
`        array_keys() expects parameter 1 to be array, string given
`

**Usage:**
`
factory: randomElement(['fhstp', 'sziu', 'upt', 'ips', 'via'])
`
_also tried:_
`
factory: randomElement(array('fhstp', 'sziu', 'upt', 'ips', 'via'))
`

Would be nice if this could be fixed. This way, we probably could randomly fill taxonomy term fields. 🙌

**Comment by aerni** [comment]
I looked into this. It's pretty complex to add this functionality. I have to add some sort of parser that gets the arguments from the string. It has to be smart enough to get arrays, multiple arguments, etc.

I started working on it but don't know if and how I'll be able to add it. If you want to PR this, go ahead.

**Comment by aerni** [comment]
This is now possible with [v1.3.0](https://github.com/aerni/statamic-factory/releases/tag/v1.3.0).
